language: android
android:
  components:
    - build-tools-26.0.2
    - build-tools-27.0.3
    - android-26
    - android-27

before_install:
#setup gcloud
  - gc_sdk_url=$(curl -s "https://cloud.google.com/sdk/downloads?hl=de" | grep -o "https.*google-cloud-sdk.*linux.*x86_64.*\\.tar\\.gz" | sed s/\\?.*//g)
  - wget -qO- ${gc_sdk_url} | tar xvz


# gcloud login
  - echo ${GOOGLE_AUTH} | base64 --decode > ${HOME}/gcp-key.json
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
  - ./google-cloud-sdk/bin/gcloud --quiet config set project ${PROJECT_ID}
# install dependencies
  - ./gradlew dependencies

script:
# unit tests
  - ./gradlew test
# ui tests
  - ./gradlew assembleAndroidTest assemble
  - APK_PATH=$(find . -path "*.apk" ! -path "*unaligned.apk" ! -path "*Test*.apk" -print -quit)
  - TEST_APK_PATH=$(find "." "-path" "*Test*.apk" -print -quit)
  - ./google-cloud-sdk/bin/gcloud firebase test android run --type instrumentation --app ${APK_PATH} --test ${TEST_APK_PATH} --device model=sailfish,version=27,locale=en,orientation=portrait --timeout 30m


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache